### PR TITLE
Update NPM api_key

### PR DESCRIPTION
**Pull request by samt**
From the travis build:

> `npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".`

Steps taken:
1. Generated new NPM token at https://www.npmjs.com/settings/~/tokens
2. Ran `$ travis encrypt $NPM_TOKEN` 
3. Replaced relevant api_key entry in `.travis.yml`

### CODE REVIEW

**Comment by monkbroc** [comment]
Did you generate the token for `particlebot` (password in 1Password)?

**Comment by monkbroc** [comment]
You can bump the patch version and push to trigger the npm publish.

**Comment by busticated** [comment]
@samt i updated the token 12 days ago 👉 https://github.com/particle-iot/particle-api-js/pull/89

did you see an actual failure related to a bad / expired npm token? i _think_ npm is just dumping out that warning regardless.

**Comment by samt** [comment]
@busticated That's odd - we noticed it wasn't working: https://travis-ci.org/particle-iot/particle-api-js/jobs/407329178#L1042

**Pull request merged**
