### PR TITLE
Fix event stream exception when it is an HTML response

### PR DESCRIPTION
**Pull request by spacetc62**
It looks like on certain kinds of bad requests, the event stream endpoints return HTML instead of JSON.  Without a catch here, this kind of exception ends up bubbling all the way up as an uncaught exception (and will kill the process, if you are exiting on uncaught exceptions).

### CODE REVIEW

**Comment by nassan** [comment]
Hi. I was going to do the same pull request. This is important, please except this pull request. :)
@spacetc62 Maybe do something like:
```
try {
    body = JSON.parse(body);
} catch(e){
    body = e
}
```
That way that error will be reported in the body for `reject` call in the `finally` clause.

Either way thanks for the pull request. And either way, please accept it, as I need this to make my codebase more stable.

**Comment by spacetc62** [comment]
Any idea when this PR could get merged and a new version released with this fix? Thanks!

**Comment by nassan** [comment]
Did anyone ever figure out the root of this bug is? @spacetc62

**Comment by spacetc62** [comment]
Nope, I'm not with Particle, so don't know why this endpoint would send back HTML sometimes.  I'm currently using a fork with this patch applied until this PR gets merged.

**Comment by monkbroc** [comment]
Sorry it took so long for someone to take a look at this PR. I'm going to work a release.

**Comment by monkbroc** [comment]
This change is out in version 7.1.0

**Pull request merged**
